# Generated by Django 4.1.1 on 2023-05-19 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_properties_userid_alter_blog_post_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='status',
            field=models.CharField(default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 5, 19)),
        ),
    ]
